// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AdminClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdateUserDto
    {
        /// <summary>
        /// Initializes a new instance of the UpdateUserDto class.
        /// </summary>
        public UpdateUserDto() { }

        /// <summary>
        /// Initializes a new instance of the UpdateUserDto class.
        /// </summary>
        public UpdateUserDto(string name = default(string), string email = default(string), string phone = default(string), string role = default(string), string password = default(string), bool? disabled = default(bool?))
        {
            Name = name;
            Email = email;
            Phone = phone;
            Role = role;
            Password = password;
            Disabled = disabled;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

        /// <summary>
        /// Possible values include: 'admin', 'visitor'
        /// </summary>
        [JsonProperty(PropertyName = "role")]
        public string Role { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "disabled")]
        public bool? Disabled { get; set; }

    }
}
