// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AdminClient
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for AppController.
    /// </summary>
    public static partial class AppControllerExtensions
    {
            /// <summary>
            /// AppController_getHello
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void GetHello(this IAppController operations)
            {
                Task.Factory.StartNew(s => ((IAppController)s).GetHelloAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// AppController_getHello
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task GetHelloAsync(this IAppController operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.GetHelloWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false);
            }

    }
}
