// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AdminClient
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// The crafts API description
    /// </summary>
    public partial interface ICrocodileHandycraft : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the ICraftsController.
        /// </summary>
        ICraftsController CraftsController { get; }

        /// <summary>
        /// Gets the IMaterialsController.
        /// </summary>
        IMaterialsController MaterialsController { get; }

        /// <summary>
        /// Gets the ICategoriesController.
        /// </summary>
        ICategoriesController CategoriesController { get; }

        /// <summary>
        /// Gets the IUsersController.
        /// </summary>
        IUsersController UsersController { get; }

        /// <summary>
        /// Gets the IPhotosController.
        /// </summary>
        IPhotosController PhotosController { get; }

        /// <summary>
        /// Gets the ICommentsController.
        /// </summary>
        ICommentsController CommentsController { get; }

        /// <summary>
        /// Gets the IAppController.
        /// </summary>
        IAppController AppController { get; }

    }
}
