// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AdminClient
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for MaterialsController.
    /// </summary>
    public static partial class MaterialsControllerExtensions
    {
            /// <summary>
            /// MaterialsController_create
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='contentType'>
            /// . Possible values include: 'application/json'
            /// </param>
            public static void Create(this IMaterialsController operations, CreateMaterialDto body, string contentType = default(string))
            {
                Task.Factory.StartNew(s => ((IMaterialsController)s).CreateAsync(body, contentType), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// MaterialsController_create
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='contentType'>
            /// . Possible values include: 'application/json'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task CreateAsync(this IMaterialsController operations, CreateMaterialDto body, string contentType = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.CreateWithHttpMessagesAsync(body, contentType, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// MaterialsController_findAll
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void FindAll(this IMaterialsController operations)
            {
                Task.Factory.StartNew(s => ((IMaterialsController)s).FindAllAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// MaterialsController_findAll
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task FindAllAsync(this IMaterialsController operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.FindAllWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// MaterialsController_remove
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            public static void Remove(this IMaterialsController operations, double id)
            {
                Task.Factory.StartNew(s => ((IMaterialsController)s).RemoveAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// MaterialsController_remove
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task RemoveAsync(this IMaterialsController operations, double id, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.RemoveWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
